# For more see: https://github.com/actions/labeler?tab=readme-ov-file#pull-request-labeler
MCMC:
  - changed-files:
      - any-glob-to-any-file: 
          - mcmc/**

Plotting:
  - changed-files:
      - any-glob-to-any-file: 
          - plotting/**
          - Diagnostics/**

Nu Osc/Xsec:
  - changed-files:
      - any-glob-to-any-file: 
          - covariance/**
          - splines/**

Samples:
  - changed-files:
      - any-glob-to-any-file: 
          - samplePDF/**

Manager:
  - changed-files:
      - any-glob-to-any-file: 
          - manager/**

Documentation:
  - changed-files:
      - any-glob-to-any-file: 
          - Doc/**
Cmake:
  - changed-files:
      - any-glob-to-any-file:
          - cmake/**
          - CMakeLists.txt

GPU:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.cu'
          - '**/*.cuh'

CI/CD:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

python:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.py'

