# Check if MaCh3 compiles correctly

name: Build CI

# The events that trigger the workflow
on:
  pull_request:
    branches: [ develop ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # KS: Prevents cancellation of remaining jobs if one fails
      matrix:
        include:
          - os: Ubuntu22.04
            file: Doc/MaCh3DockerFiles/Ubuntu22.04/Dockerfile
            tag: ubuntu22.04latest
          - os: Alma9
            file: Doc/MaCh3DockerFiles/Alma9/Dockerfile
            tag: alma9latest
          - os: Fedora32
            file: Doc/MaCh3DockerFiles/Fedora32/Dockerfile
            tag: fedora32latest

    name: Build CI ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file ${{ matrix.file }} --tag ghcr.io/${{ github.repository_owner }}/mach3:${{ matrix.tag }} --build-arg MACH3_VERSION=${{ github.head_ref }}
